### ISSUE TITLE
Unable to install version 2.x.x on Ubuntu

### ISSUE THREAD

**Issue by A-Scott-Rowe** [treasure-data/chef-td-agent#106]
I am having trouble with the cookbook with Chef 11 on Ubuntu 14.04

receiving `uninitialized constant Fluent::ExMonitorAgentInput::MONITOR_INFO (NameError)` from chef with custom json(as YAML)
```  
  td_agent:
    api_key: <API_KEY>
    plugins: ['filter']
    version: '2'
    includes: true
```

I believe the problem is that it is not installing the correct version of td-agent/fluentd (should be td-agent 2.x.x fluentd 0.12.x)

```
$ fluentd --version
fluentd 1.0.0
``` 

when I try and pin the version it seems like it is not getting into the recipe.

```  
  td_agent:
    api_key: <API_KEY>
    plugins: ['filter']
    version: '2.3.6'
    pin_version: true
    includes: true
```

results in 

```
http://packages.treasuredata.com/0/ubuntu/trusty/dists/trusty/contrib/binary-amd64/Packages  404  Not Found [IP: 54.230.19.91 80]
```

any advice? is my config wrong?
